import SwiftUI
import AppKit
import NewbroExecutorCore

/// Simplified bro silhouette used only as a fallback if the bundled logo
/// silhouette (`MenuBarBro.png`) is missing. Designed in a 24×24 space; the eyes
/// and mouth are even-odd cut-outs.
struct BroShape: Shape {
    func path(in rect: CGRect) -> Path {
        let s = min(rect.width, rect.height) / 24.0
        let ox = rect.minX, oy = rect.minY
        func P(_ x: CGFloat, _ y: CGFloat) -> CGPoint { CGPoint(x: ox + x * s, y: oy + y * s) }
        func Rt(_ x: CGFloat, _ y: CGFloat, _ w: CGFloat, _ h: CGFloat) -> CGRect {
            CGRect(x: ox + x * s, y: oy + y * s, width: w * s, height: h * s)
        }
        var path = Path()
        path.addRoundedRect(in: Rt(5, 4, 14, 16), cornerSize: CGSize(width: 7 * s, height: 7 * s))
        path.addEllipse(in: Rt(9.4 - 1.7, 11.2 - 1.7, 3.4, 3.4))
        path.addEllipse(in: Rt(14.6 - 1.7, 11.2 - 1.7, 3.4, 3.4))
        path.move(to: P(10.2, 14.0))
        path.addQuadCurve(to: P(13.8, 14.0), control: P(12, 16.0))
        path.addQuadCurve(to: P(10.2, 14.0), control: P(12, 15.0))
        path.closeSubpath()
        return path
    }
}

/// The menu bar icon: the brand logo silhouette as a **template** `NSImage`, so
/// the system tints it to contrast with the menu bar automatically (white on a
/// dark bar, dark on a light one — including the light-mode/dark-wallpaper case
/// that `NSApp.effectiveAppearance` cannot detect). Loaded from
/// `Contents/Resources/MenuBarBro.png` (generated by tools/make-menubar-icon.sh);
/// falls back to the drawn `BroShape` if the asset is missing.
@MainActor func menuBarBroTemplate() -> NSImage {
    if let url = Bundle.main.url(forResource: "MenuBarBro", withExtension: "png"),
       let image = NSImage(contentsOf: url) {
        image.isTemplate = true
        image.size = NSSize(width: 18, height: 18)
        return image
    }
    let renderer = ImageRenderer(content: BroShape()
        .fill(Color.black, style: FillStyle(eoFill: true))
        .frame(width: 18, height: 18))
    renderer.scale = 2
    let image = renderer.nsImage ?? NSImage(size: NSSize(width: 18, height: 18))
    image.isTemplate = true
    return image
}

extension StatusTone {
    /// Intentional, non-adaptive status colors (same values as the design spec):
    /// ready green, busy amber, attention red, idle gray.
    var nsColor: NSColor {
        switch self {
        case .ok:        return NSColor(srgbRed: 0.063, green: 0.725, blue: 0.506, alpha: 1) // #10b981
        case .busy:      return NSColor(srgbRed: 0.961, green: 0.620, blue: 0.043, alpha: 1) // #f59e0b
        case .attention: return NSColor(srgbRed: 0.937, green: 0.267, blue: 0.267, alpha: 1) // #ef4444
        case .idle:      return NSColor(srgbRed: 0.612, green: 0.639, blue: 0.686, alpha: 1) // #9ca3af
        }
    }

    /// A non-template colored dot for the per-profile menu rows (NSMenu renders
    /// non-template images in their own color).
    func dotImage(diameter: CGFloat = 9) -> NSImage {
        let size = NSSize(width: diameter, height: diameter)
        let image = NSImage(size: size)
        image.lockFocus()
        nsColor.setFill()
        NSBezierPath(ovalIn: NSRect(origin: .zero, size: size)).fill()
        image.unlockFocus()
        image.isTemplate = false
        return image
    }
}
